fix: expand spec, keep server url
ogen-go/ogen pull request #1072
Opened 2023-10-17 07:55 UTC by max107

fix: keep server url in extended spec

2023-10-24 14:38 UTC, tdakkota requested changes

2023-10-24 14:38 UTC, tdakkota commented on openapi/parser/expand.go
> +	expanded.URL = s.URL
Variable `template` already contains stringified server URL template.

This line should be at the end of the function:
```go
expanded.URL = template.String()
```

2023-10-25 05:42 UTC, tdakkota requested changes
Could you rebase your PR?

Also, fix commit title according to [Conventional Commits](https://github.com/conventional-changelog/commitlint/tree/master/%40commitlint/config-conventional#type-enum), please.

2023-10-25 05:42 UTC, tdakkota commented on openapi/server.go
> +	URL         string
This field is unused.

2023-10-25 14:20 UTC, max107 commented
https://github.com/ogen-go/ogen/pull/1079

2023-10-25 14:20 UTC, closed without merging