Improve bearer security template.
ogen-go/ogen pull request #723
Opened 2022-12-13 16:06 UTC by egor-gorlin-exinity

Verify auth scheme and populate correct token value.

2022-12-14 07:28 UTC, egor-gorlin-exinity commented
Hi! Sorry for messed up pipeline. Tried to fix reported warnings

2022-12-14 20:00 UTC, tdakkota requested changes

2022-12-14 20:00 UTC, tdakkota commented on gen/_template/security.tmpl
> +		t.Token = headerParts[1]
```suggestion
		scheme, token, ok := strings.Cut(req.Header.Get("Authorization"), " ")
		if !ok {
			return nil, errors.New("invalid bearer auth")
		}
		if !strings.EqualFold(scheme, "Bearer") {
			return nil, errors.Errorf("invalid auth scheme: %q", scheme)
		}
		t.Token = token
```

2022-12-15 09:09 UTC, ernado commented
Please re-generate

2022-12-17 02:13 UTC, tdakkota approved these changes

2022-12-17 03:14 UTC, merged