feat(gen): No NPE on default stream responses
ogen-go/ogen pull request #875
Opened 2023-04-24 20:43 UTC by natehart

The current implementation of the templated stream response `Read(byte[])` function uses the `Data io.Reader` field without first checking for `nil`.

Users who want to return a value with an empty body are forced to explicitly specify an empty `io.Reader` rather than simply ignore the field and get use from the empty struct.

This commit adds a `nil` check before using the `Data` field and, if it is `nil`, responds as if it were an empty `io.Reader` instead of panicking.

This will hopefully make this library slightly more ergonomic to use.

2023-04-24 21:40 UTC, tdakkota requested changes
Push `chore: commit generated files` commit to this PR branch, please.

The change itself looks good to me. Thank you for contribution.

2023-04-25 06:46 UTC, ernado commented
Hi! Please

1. Change commit message with lowercase `No`, commitlint requries it
2. Add commit from #876

2023-04-25 18:26 UTC, ernado commented
I think you need to rebase instead of merge, so merge commit won’t be in your branch 🙃

2023-04-25 21:08 UTC, natehart commented
Derp. That's what I get for using GitHub's options...

2023-04-26 01:37 UTC, tdakkota approved these changes

2023-04-26 01:37 UTC, merged