fix(gen): use mapping key for discriminator const
ogen-go/ogen pull request #973
Opened 2023-07-09 10:37 UTC by Liooo

Closes: https://github.com/ogen-go/ogen/issues/967

Just changing the generated string constant
This won't allow us to use the same value as was stated in https://github.com/ogen-go/ogen/issues/967#issue-1787529410.

Please tell me if any changes to be made are missing.

2023-07-09 10:42 UTC, Liooo commented
I ran go generate and noticed there's more to be done. making this draft.

2023-07-10 16:10 UTC, Liooo commented
@tdakkota 

Please review, at least CI is passing.

2023-07-10 18:33 UTC, tdakkota requested changes
One small change in a template.

Everything else is fine.  Thank you!

2023-07-10 18:33 UTC, ghost commented on gen/_template/schema/sum.tmpl
> +	{{- if ne $m nil }}
```suggestion
	{{- if $m }}
```

2023-07-11 01:00 UTC, Liooo commented on gen/_template/schema/sum.tmpl
> +	{{- if ne $m nil }}
@tdakkota thank you

2023-07-11 02:00 UTC, tdakkota approved these changes

2023-07-11 02:00 UTC, merged